# Generated by Django 4.2.1 on 2023-07-29 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='adminHod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='documents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='employes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=255)),
                ('profile_pic', models.FileField(upload_to='')),
                ('adress', models.TextField()),
                ('session_start_year', models.DateField()),
                ('session_end_year', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utilisateur.documents')),
            ],
        ),
        migrations.CreateModel(
            name='Mstage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='personnels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPersonnel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('personnel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.personnels')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationEmploye',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('Employé_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.employes')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='utilisateur.discussion')),
            ],
        ),
        migrations.CreateModel(
            name='leaveReportPersonnel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_date', models.CharField(max_length=255)),
                ('leave_message', models.TextField()),
                ('leave_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('personnel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.personnels')),
            ],
        ),
        migrations.CreateModel(
            name='leaveReportEmploye',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_date', models.CharField(max_length=255)),
                ('leave_message', models.TextField()),
                ('leave_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('Employé_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.employes')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackReportPersonnel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.TextField()),
                ('feedback_reply', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('personnel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.personnels')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBackEmploye',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.TextField()),
                ('feedback_reply', models.TextField()),
                ('leave_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('Employé_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.employes')),
            ],
        ),
        migrations.CreateModel(
            name='E_stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('arriver', models.DateTimeField(default=False)),
                ('depart', models.DateField(default=False)),
                ('MS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.mstage')),
            ],
        ),
        migrations.CreateModel(
            name='communiquers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('communiquer_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.documents')),
                ('personnels_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.personnels')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=1000)),
                ('upload_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='book/pdf/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='book/image/')),
                ('MS', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilisateur.mstage')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('Employé_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utilisateur.employes')),
                ('attendance_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.attendance')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='communiquer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utilisateur.communiquers'),
        ),
    ]
